Restaurant Page Pull request
NataJenkins/RestaurantPage pull request #1
Opened 2021-03-29 20:56 UTC by NataJenkins

Page build with html, css and Javascript  of a restaurant page in which you can navigate through tabs

2021-03-29 22:35 UTC, uche-inyama requested changes
## Invalid Submission

### Hi @NataJenkins :wave: 

I have marked this submission as invalid, this is because your last commit failed linter validation. Passing linter validation is a hard requirement. Kindly refer to this [link](https://microverse.zendesk.com/hc/en-us/articles/1500002085202-February-2nd-2021-linter-errors-as-a-reason-of-project-invalidation-#) for more details.

Ensure your commits pass linter validations, then submit another form for a code review. 

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

2021-03-29 22:49 UTC, uche-inyama requested changes
## Changes Required

### Hi @NataJenkins :wave: 

There are few updates to make:

* [ ] Webpack-dev-server should be installed as devDependencies in package.json(
[screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/devdep_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59622983/))

In your package.json the **scripts** property should look like so:


```
    "scripts": {
        "dev": "webpack --mode development",
        "build": "webpack --mode production",
        "start": "webpack-dev-server --mode development --open" // optional
      },
```
* [ ] When Navigating the application, if I click on the **home menu**, the navigation bar disappears but re-emerges when I reload the page. Please do fix that.

Make these changes, then submit another form for a code review.


### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

2021-03-30 03:14 UTC, rukundoeric commented on src/index.js
> +// import "./styless.css";
remove this comment

2021-03-30 03:15 UTC, rukundoeric commented on src/tabs.js
> +  //   event.target.parentElement.className += " active";
remove this comment

2021-03-30 03:16 UTC, rukundoeric approved these changes
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve
  - [x]  Kindly remove all commented lines of code before you merge.

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

2021-03-30 04:07 UTC, merged